/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko;

import toko.Konfigurasi;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PowerUp
 */
public class data_barang extends javax.swing.JFrame {

    public data_barang() {
        initComponents();
        load_table();
        kosong();
        auto_code();
    }
    
    private void auto_code(){
    try{
        String sql = "SELECT MAX(kode_barang) as kode FROM barang ";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
                Object[ ] obj = new Object[1];
                obj[0] = rs.getString("kode");
                if(obj[0] == null){
                    obj[0] = "000";
                }
                String str_kd = (String) obj[0];
                String kd = str_kd.substring(0,3);//P0000
                int int_kode = Integer.parseInt(kd);
                int_kode++;
                String a = String.format("%03d", int_kode);
                String b = a;
                txt_kode.setText(b);
                txt_kode.setEditable(false);
            }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_harga_beli = new javax.swing.JTextField();
        txt_cari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_harga_jual = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_kode = new javax.swing.JTextField();
        txt_type = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_haps = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 30));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 60, -1));

        txt_harga_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_harga_beliActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, -1));

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 260, -1));

        jLabel4.setText("Type Barang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel5.setText("Harga jual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabel6.setText("Kode Barang");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel7.setText("Nama Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel10.setText("Harga beli");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));
        jPanel1.add(txt_harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 160, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 160, -1));
        jPanel1.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 160, -1));
        jPanel1.add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 500, 160));

        btn_simpan.setBackground(new java.awt.Color(51, 153, 255));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan ");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        btn_cetak.setBackground(new java.awt.Color(51, 153, 255));
        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setText("Cetak ");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 70, -1));

        btn_edit.setBackground(new java.awt.Color(51, 153, 255));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 70, -1));

        btn_batal.setBackground(new java.awt.Color(255, 0, 0));
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, -1));

        btn_haps.setBackground(new java.awt.Color(255, 0, 0));
        btn_haps.setForeground(new java.awt.Color(255, 255, 255));
        btn_haps.setText("Hapus");
        btn_haps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_haps, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 70, -1));

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 30));

        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 150, 30));

        usernamebrg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(usernamebrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, 26));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/brgRev2.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_harga_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_harga_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_harga_beliActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
  try {
           String sql= "INSERT INTO barang VALUES ('"+txt_kode.getText()+"','"
             +txt_nama.getText()+"','"+txt_type.getText()+"','"+txt_harga_beli.getText()
             +"','"+txt_harga_jual.getText()+"',"+0+")";
             java.sql.Connection conn =(Connection)Konfigurasi.configDB();
             java.sql.PreparedStatement pst=conn.prepareStatement (sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "penyimpanan data berhasil");
       }catch (Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
          load_table();
        kosong();
        auto_code();
    }//GEN-LAST:event_btn_simpanActionPerformed
    private void load_table() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Type Barang");
    model.addColumn("Harga beli");
    model.addColumn("Harga jual");
    model.addColumn("stok");
    
  
    
    try {
        int no=1;
        String sql ="select *from barang";
         java.sql.Connection conn =(Connection)Konfigurasi.configDB();
         java.sql.Statement stm=conn.createStatement();
         java.sql.ResultSet res=stm.executeQuery(sql);
         while (res.next()){
             model.addRow(new Object[] {no++,res.getString(1),
             res.getString(2),res.getString(3),res.getString(4),
             res.getString(5),res.getString(6)});
         }
         jTable1.setModel(model);
    }catch (Exception e){
    }
    
    }
private void kosong (){
    txt_cari.setText(null);
    txt_kode.enable();
    txt_kode.setText(null);
    txt_nama.setText(null);
    txt_type.setText(null);
    txt_harga_beli.setText(null);
    txt_harga_jual.setText(null);
    load_table();
   }
 private void loadtable2() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Type Barang");
    model.addColumn("Harga beli");
    model.addColumn("Harga jual");
    model.addColumn("stok");
    
  
    
    try {
        int no=1;
        String sql ="select *from barang WHERE kode_barang='"+txt_cari.getText()+"' OR nama_barang LIKE '%"+txt_cari.getText() +"%'";
         java.sql.Connection conn =(Connection)Konfigurasi.configDB();
         java.sql.Statement stm=conn.createStatement();
         java.sql.ResultSet res=stm.executeQuery(sql);
         while (res.next()){
             model.addRow(new Object[] {no++,res.getString(1),
             res.getString(2),res.getString(3),res.getString(4),
             res.getString(5),res.getString(6)});
         }
         jTable1.setModel(model);
    }catch (Exception e){
    }
    
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
  int baris =jTable1.rowAtPoint(evt.getPoint());
    String kode_barang = jTable1.getValueAt(baris,1).toString();
    txt_kode.setText(kode_barang);
    txt_kode.disable();
    if (jTable1.getValueAt(baris,2)==null){
    txt_nama.setText("");
    }else {
      txt_nama.setText(jTable1.getValueAt(baris,2).toString());
    }
    if (jTable1.getValueAt(baris,3)==null){
   txt_type.setText("");
    }else {
   txt_type.setText(jTable1.getValueAt(baris,3).toString());
    }                                    
if (jTable1.getValueAt(baris,4)==null){
    txt_harga_beli.setText("");
    }else {
      txt_harga_beli.setText(jTable1.getValueAt(baris,4).toString());
}
  if (jTable1.getValueAt(baris,4)==null){
    txt_harga_jual.setText("");
    }else {
      txt_harga_jual.setText(jTable1.getValueAt(baris,5).toString());
}
//if (jTable1.getValueAt(baris,5)==null){
   // txt_stok.setText("");
   // }else {
     // txt_stok.setText(jTable1.getValueAt(baris,6).toString());
//}
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
       kosong();
       auto_code();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapsActionPerformed
    int respons = JOptionPane.showConfirmDialog(this, "Yakin Ingin Menghapus ?", "Hapus Barang", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respons==JOptionPane.YES_OPTION) {
        try {
           String sql= "DELETE FROM barang where kode_barang ='"+txt_kode.getText()+"'";
             java.sql.Connection conn =(Connection)Konfigurasi.configDB();
             java.sql.PreparedStatement pst=conn.prepareStatement (sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di hapus");
       }catch (Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
    }
        }
     load_table();
        kosong();
        auto_code();
   
    }//GEN-LAST:event_btn_hapsActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
     try {
           String sql= "UPDATE barang SET "
             +" nama_barang='"+txt_nama.getText()
             +"',type_barang='"+txt_type.getText()+"',harga_beli='"+txt_harga_beli.getText()
             +"',harga_jual='"+txt_harga_jual.getText()
             +"' WHERE kode_barang='"+ txt_kode.getText()+"'";
             java.sql.Connection conn =(Connection)Konfigurasi.configDB();
             java.sql.PreparedStatement pst=conn.prepareStatement (sql);
            pst.execute();          
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, "perubahan data gagal" 
                   +e.getMessage());
       }load_table();
        kosong();
        auto_code();
    }//GEN-LAST:event_btn_editActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
  
    }//GEN-LAST:event_txt_cariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    loadtable2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
    try{
        jTable1.print();
        JOptionPane.showMessageDialog(null,"sedang mencetak");
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"maap data table anda kosong");
    }
 auto_code();   
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new laporanAwal().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int respons = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar ?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respons==JOptionPane.YES_OPTION) {
        this.setVisible(false);
        new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_edit;
    private javax.swing.JToggleButton btn_haps;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_harga_beli;
    private javax.swing.JTextField txt_harga_jual;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_type;
    public static final javax.swing.JLabel usernamebrg = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    
    }

