/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class laporanAwal extends javax.swing.JFrame {

    /**
     * Creates new form laporanAwal
     */
    public laporanAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_lapPnjl = new javax.swing.JButton();
        btn_lapPmbl = new javax.swing.JButton();
        btn_out = new javax.swing.JButton();
        btn_dsh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_lapPnjl.setBorder(null);
        btn_lapPnjl.setContentAreaFilled(false);
        btn_lapPnjl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapPnjlActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lapPnjl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 140, 120));

        btn_lapPmbl.setBorder(null);
        btn_lapPmbl.setContentAreaFilled(false);
        btn_lapPmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapPmblActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lapPmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 140, 120));

        btn_out.setBorder(null);
        btn_out.setContentAreaFilled(false);
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });
        jPanel1.add(btn_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 40));

        btn_dsh.setBorder(null);
        btn_dsh.setContentAreaFilled(false);
        btn_dsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dsh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 40));

        usernameLap1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(usernameLap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Lap2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dshActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dshActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        int respons = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar ?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respons==JOptionPane.YES_OPTION) {
        this.setVisible(false);
        new Login().setVisible(true);
        }
    }//GEN-LAST:event_btn_outActionPerformed

    private void btn_lapPnjlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapPnjlActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new lapPnjl().setVisible(true);
    }//GEN-LAST:event_btn_lapPnjlActionPerformed

    private void btn_lapPmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapPmblActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new lapPmbl().setVisible(true);
                                          
    }//GEN-LAST:event_btn_lapPmblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dsh;
    private javax.swing.JButton btn_lapPmbl;
    private javax.swing.JButton btn_lapPnjl;
    private javax.swing.JButton btn_out;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel usernameLap1 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
