/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class lapPmbl extends javax.swing.JFrame {

    /**
     * Creates new form lapPmbl
     */
    public lapPmbl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_out = new javax.swing.JButton();
        btn_lap = new javax.swing.JButton();
        btn_dsh = new javax.swing.JButton();
        lap_thn = new javax.swing.JButton();
        lap_hari = new javax.swing.JButton();
        lap_bln = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_out.setBorder(null);
        btn_out.setContentAreaFilled(false);
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });
        jPanel1.add(btn_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 40));

        btn_lap.setBorder(null);
        btn_lap.setContentAreaFilled(false);
        btn_lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 150, 40));

        btn_dsh.setBorder(null);
        btn_dsh.setContentAreaFilled(false);
        btn_dsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dsh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 40));

        lap_thn.setBorder(null);
        lap_thn.setContentAreaFilled(false);
        lap_thn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_thnActionPerformed(evt);
            }
        });
        jPanel1.add(lap_thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 140, 130));

        lap_hari.setBorder(null);
        lap_hari.setContentAreaFilled(false);
        lap_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_hariActionPerformed(evt);
            }
        });
        jPanel1.add(lap_hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 113, 140, 130));

        lap_bln.setBorder(null);
        lap_bln.setContentAreaFilled(false);
        lap_bln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_blnActionPerformed(evt);
            }
        });
        jPanel1.add(lap_bln, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 140, 130));

        usernameLap3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(usernameLap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LAPPmblREV.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lap_blnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_blnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Pmbl_bln().setVisible(true);
    }//GEN-LAST:event_lap_blnActionPerformed

    private void btn_dshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dshActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dshActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        int respons = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar ?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respons==JOptionPane.YES_OPTION) {
        this.setVisible(false);
        new Login().setVisible(true);
        }
    }//GEN-LAST:event_btn_outActionPerformed

    private void btn_lapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new laporanAwal().setVisible(true);
    }//GEN-LAST:event_btn_lapActionPerformed

    private void lap_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_hariActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Pmbl_hr().setVisible(true);
    }//GEN-LAST:event_lap_hariActionPerformed

    private void lap_thnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_thnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Pmbl_thn().setVisible(true);
    }//GEN-LAST:event_lap_thnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lapPmbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lapPmbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lapPmbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lapPmbl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lapPmbl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dsh;
    private javax.swing.JButton btn_lap;
    private javax.swing.JButton btn_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lap_bln;
    private javax.swing.JButton lap_hari;
    private javax.swing.JButton lap_thn;
    public static final javax.swing.JLabel usernameLap3 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
