package toko;


import java.awt.Graphics;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import toko.Dashboard;
import static toko.penjualan2.txt_kasir;
import static toko.penjualan2.txt_nota1;
import static toko.penjualan2.username_pnj;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class nota extends javax.swing.JFrame {

    /** Creates new form nota */
    public nota() {
        initComponents();
        
        load_table();
        muncul();
        noedit();
        pnj();
        
        
        
    }
    
    private void load_table() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Quantity");
        model.addColumn("Harga Satuan");
        model.addColumn("Sub Total");

        try {
            int no=1 ;
            String sql = "SELECT barang.kode_barang, barang.nama_barang, detail_jual.jumlah, barang.harga_jual, detail_jual.sub_total " +
            " FROM penjualan "
            +" JOIN detail_jual ON detail_jual.nota_penjualan = penjualan.nota_penjualan " +
            " JOIN barang on barang.kode_barang = detail_jual.kode_barang " +
            " WHERE penjualan.nota_penjualan = '"+ txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet res = pst.executeQuery(sql);
            while(res.next()) {
                model.addRow(new Object[]{no++,res.getString(1)
                ,res.getString(2),res.getString(3),res.getString(4)
                ,res.getString(5)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
  
    
    private void kembalian(){
         
    int gtotal = Integer.parseInt(txt_grandTtl.getText());
    int bayar = Integer.parseInt(txt_bayar.getText());
   
    int kembali  = bayar - gtotal;
    txt_kembali.setText(String.valueOf(kembali));
    }
    
    private void muncul(){
    txt_nota.setText(txt_nota1.getText());
    txt_kasirnt.setText(txt_kasir.getText());
    }
    
    private void pnj(){
    try{
        String sql = "SELECT sum(detail_jual.sub_total), penjualan.tgl_penjualan "
                + " FROM penjualan join detail_jual "
                + " on penjualan.nota_penjualan = detail_jual.nota_penjualan"
                + " WHERE penjualan.nota_penjualan='"+txt_nota1.getText() +"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
            txt_grandTtl.setText(rs.getString(1));
            txt_tgl.setText(rs.getString(2));
            }else {
                JOptionPane.showMessageDialog(null, sql);
            }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }
    
    private void noedit(){
    txt_tgl.setEditable(false);
    txt_kasirnt.setEditable(false);
    txt_nota.setEditable(false);
    txt_grandTtl.setEditable(false);
    txt_kembali.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_kasirnt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_grandTtl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nota Penjualan : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txt_nota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_nota.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jPanel1.add(txt_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, -1));

        jLabel4.setText("Tgl Penjualan    : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txt_tgl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, -1));

        jLabel5.setText("Kasir                    : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txt_kasirnt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txt_kasirnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, -1));

        jLabel9.setText("Bayar            : Rp.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 130, -1));

        jLabel10.setText("Kembali       : Rp.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        txt_kembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kembaliKeyReleased(evt);
            }
        });
        jPanel1.add(txt_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 130, -1));

        jLabel11.setText("Grand Total : Rp.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));
        jPanel1.add(txt_grandTtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Barang", "Nama Barang", "Quantity", "Harga_satuan", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 620, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Nota 4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btn_dashboard.setText("Dashboard");
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cetak)
                .addGap(19, 19, 19)
                .addComponent(btn_dashboard)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cetak)
                    .addComponent(btn_dashboard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
         int kembali = Integer.parseInt(txt_kembali.getText());
        
        if(kembali<0){
                JOptionPane.showMessageDialog(null, "Maaf Uang Pembayaran Kurang!");
                txt_bayar.setText("");
                txt_kembali.setText("");
            }else{
        this.setVisible(false);
        new Dashboard().setVisible(true);
        }
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void txt_kembaliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kembaliKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_kembaliKeyReleased

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
       int kembali = Integer.parseInt(txt_kembali.getText());
        
        if(kembali<0){
                JOptionPane.showMessageDialog(null, "Maaf Uang Pembayaran Kurang!");
                txt_bayar.setText("");
                txt_kembali.setText("");
            }else{
        
        try {
            String sql = "UPDATE penjualan SET Bayar ="+txt_bayar.getText()+ ", Kembalian= "+txt_kembali.getText()
                    + " WHERE nota_penjualan ='"+txt_nota1.getText()+"'";
            java.sql.Connection conn =(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            //Statement stm = conn.createStatement();
            
            try {
                
                String report = ("C:\\Dev\\Tutorial java\\Kasir\\src\\toko\\reportNota.jrxml");
                
                HashMap hash = new HashMap();
                hash.put("nota_penjualan", txt_nota1.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, conn);
                JasperViewer.viewReport(JPrint, false);
            
            }catch (Exception rptextcpt) {
            JOptionPane.showMessageDialog(this, rptextcpt.getMessage());
        }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void txt_bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_bayarKeyPressed

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        // TODO add your handling code here:
        kembalian();
    }//GEN-LAST:event_txt_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_grandTtl;
    private javax.swing.JTextField txt_kasirnt;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_nota;
    private javax.swing.JTextField txt_tgl;
    // End of variables declaration//GEN-END:variables

    
}
