package toko;


import toko.Dashboard;
import toko.Login;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static toko.Dashboard.txt_nota;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class penjualan2 extends javax.swing.JFrame {

    /**
     * Creates new form penjualan2
     */
    public penjualan2() {
        initComponents();
        nama_kasir();
        input();
        gkedit();
       //total();
        //hitung();
        //load_table();
    }
    
    public final void input(){
    txt_nota1.setText(txt_nota.getText());
    txt_nota1.setEditable(false);
    }
    
    private void nama_kasir() {
    try{
        String sql = "SELECT nama_kasir FROM user WHERE username='"+username_pnj.getText() +"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
            txt_kasir.setText(rs.getString(1));
            }else {
                JOptionPane.showMessageDialog(null, sql);
            }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    txt_kasir.setEditable(false);
    }
    
    private void gkedit(){
    txt_nama_brg.setEditable(false);
    txt_harga_brg.setEditable(false);
    txt_subTtl.setEditable(false);
    txt_qty.setEditable(false);
    txt_gtotal.setEditable(false);
    }
    
    private void hitung(){
    int harga = Integer.parseInt(txt_harga_brg.getText());
    int qty = Integer.parseInt(txt_qty.getText());
   
    int subTtl  = harga * qty;
    txt_subTtl.setText(String.valueOf(subTtl));
    
    }
    
    private void kosong(){
    txt_kode_barang.setText(null);
    txt_nama_brg.setText(null);
    txt_harga_brg.setText(null);
    txt_qty.setText(null);
    txt_subTtl.setText(null);
    }
    
    private void total(){
     try {
            String sql = "SELECT SUM(sub_total) FROM detail_jual WHERE nota_penjualan='"+txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txt_gtotal.setText(rs.getString(1));
                
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void httpRequest(){
        
    }
    
    //private void load_table() {
        // membuat tampilan model tabel
        //DefaultTableModel model = new DefaultTableModel();
        //model.addColumn("no");
        //model.addColumn("Kode_Brg");
        //model.addColumn("Nama_Brg");
        //model.addColumn("Quantity");
        //model.addColumn("Harga_Satuan");
        //model.addColumn("Sub_total");
        //jTable2.setModel(model);
      
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_dashboard = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_harga_brg = new javax.swing.JTextField();
        txt_qty = new javax.swing.JTextField();
        txt_kode_barang = new javax.swing.JTextField();
        txt_nama_brg = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_edit_brg = new javax.swing.JButton();
        btn_batal_brg = new javax.swing.JButton();
        txt_gtotal = new javax.swing.JTextField();
        btn_laporan = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txt_subTtl = new javax.swing.JTextField();
        btn_tambah_brg1 = new javax.swing.JButton();
        btn_cari_brg = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Quantity", "Harga Satuan", "Sub Total"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(25);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 550, 100));

        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setBorder(null);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        jLabel4.setText("Tgl Penjualan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel5.setText("Kasir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel7.setText("Nama Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel1.setText("Nota Penjualan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel6.setText("Kode/Inisial Barang");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel9.setText("Harga Satuan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        txt_nota1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_nota1.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jPanel1.add(txt_nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 110, -1));
        jPanel1.add(txt_harga_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 130, -1));

        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qtyKeyReleased(evt);
            }
        });
        jPanel1.add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 130, -1));

        txt_kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kode_barangActionPerformed(evt);
            }
        });
        jPanel1.add(txt_kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 130, -1));

        txt_kasir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kasirActionPerformed(evt);
            }
        });
        jPanel1.add(txt_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 150, -1));
        jPanel1.add(txt_nama_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, -1));

        btn_bayar.setText("Bayar");
        btn_bayar.setBorder(null);
        btn_bayar.setContentAreaFilled(false);
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 90, 30));

        btn_batal.setText("Batal");
        btn_batal.setBorder(null);
        btn_batal.setContentAreaFilled(false);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 90, 30));

        btn_edit_brg.setText("<< Edit Brg >>");
        btn_edit_brg.setBorder(null);
        btn_edit_brg.setContentAreaFilled(false);
        btn_edit_brg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_edit_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_brgActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 120, 30));

        btn_batal_brg.setText("<< Batal Barang");
        btn_batal_brg.setBorder(null);
        btn_batal_brg.setContentAreaFilled(false);
        btn_batal_brg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_batal_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_brgActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 120, 30));

        txt_gtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_gtotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txt_gtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 190, 30));

        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan");
        btn_laporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setEnabled(false);
        btn_laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));

        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_keluar.setContentAreaFilled(false);
        btn_keluar.setEnabled(false);
        btn_keluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 30));

        txt_tgl.setDateFormatString("MMM, d, yyyy");
        jPanel1.add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 170, -1));

        jLabel10.setText("Sub Total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
        jPanel1.add(txt_subTtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 130, -1));

        username_pnj.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(username_pnj, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, 30));

        btn_tambah_brg1.setText("Tambahkan >>");
        btn_tambah_brg1.setBorder(null);
        btn_tambah_brg1.setContentAreaFilled(false);
        btn_tambah_brg1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_tambah_brg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_brg1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah_brg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 313, 120, 30));

        btn_cari_brg.setText("Cari");
        btn_cari_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_brgActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cari_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 60, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Rp.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pnj fix.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kode_barangActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from penjualan WHERE nota_penjualan='"+txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:  
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tgl = String.valueOf(fm.format(txt_tgl.getDate()));
        try {
            String sql = "UPDATE penjualan set username = '"+username_pnj.getText()+"', grand_total =" 
                    +txt_gtotal.getText()+", tgl_penjualan = '"+tgl+"'"+"WHERE nota_penjualan ='"+ txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.setVisible(false);
        new nota().setVisible(true);
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void txt_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kasirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void btn_cari_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_brgActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "SELECT nama_barang, harga_jual, kode_barang FROM barang WHERE kode_barang='"+txt_kode_barang.getText() +"' OR nama_barang LIKE '%"+txt_kode_barang.getText() +"%'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txt_nama_brg.setText(rs.getString(1));
                txt_harga_brg.setText(rs.getString(2));
                txt_kode_barang.setText(rs.getString(3));
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kode Barang Salah!!");
        }
        txt_qty.setEditable(true);
       
    }//GEN-LAST:event_btn_cari_brgActionPerformed

    private void txt_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyReleased
        // TODO add your handling code here:
        int qty = Integer.parseInt(txt_qty.getText());
        try {
            String sql = "SELECT stok FROM barang WHERE kode_barang='"+txt_kode_barang.getText() +"' OR nama_barang LIKE '%"+txt_kode_barang.getText() +"%'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                int stok = rs.getInt(1);
                if(stok<qty){
                JOptionPane.showMessageDialog(null, "Maaf Stok Tidak Mencukupi");
                kosong();
                }
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        hitung();
        
    }//GEN-LAST:event_txt_qtyKeyReleased

    private void btn_tambah_brg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_brg1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if(txt_kode_barang.getText().trim().equals("") || txt_qty.getText().trim().equals("") || txt_nama_brg.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Data Yang Dimasukkan Belum Lengkap");
        }else{
        model.addRow(new Object[]{txt_kode_barang.getText(),txt_nama_brg.getText(),txt_harga_brg.getText(),
        txt_qty.getText(),txt_subTtl.getText()});
        }
        try {
            String sql = "INSERT INTO detail_jual VALUES ('"+txt_nota1.getText()+"','"+txt_kode_barang.getText()+"',"+txt_subTtl.getText()+","+txt_qty.getText()+")";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        total();
    }//GEN-LAST:event_btn_tambah_brg1ActionPerformed

    private void btn_batal_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_brgActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if (jTable2.getSelectedRow() == -1){
            if (jTable2.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Dalam Tabel");
            }else{
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Akan Dihapus");
            }
        }else{
        model.removeRow(jTable2.getSelectedRow());
        }
        try {
            String sql = "Delete from detail_jual WHERE kode_barang= '"+txt_kode_barang.getText()+"'AND nota_penjualan='"+txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        total();
    }//GEN-LAST:event_btn_batal_brgActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        txt_kode_barang.setText(model.getValueAt(jTable2.getSelectedRow(),0).toString());
        txt_nama_brg.setText(model.getValueAt(jTable2.getSelectedRow(),1).toString());
        txt_harga_brg.setText(model.getValueAt(jTable2.getSelectedRow(),2).toString());
        txt_qty.setText(model.getValueAt(jTable2.getSelectedRow(),3).toString());
        txt_subTtl.setText(model.getValueAt(jTable2.getSelectedRow(),4).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void btn_edit_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_brgActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if (jTable2.getSelectedRow() == -1){
            if (jTable2.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Dalam Tabel");
            }else{
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Akan Diubah");
            }
        }else{
        model.setValueAt(txt_kode_barang.getText(), jTable2.getSelectedRow(),0);
        model.setValueAt(txt_nama_brg.getText(), jTable2.getSelectedRow(),1);
        model.setValueAt(txt_harga_brg.getText(),jTable2.getSelectedRow(),2);
        model.setValueAt(txt_qty.getText(), jTable2.getSelectedRow(),3);
        model.setValueAt(txt_subTtl.getText(), jTable2.getSelectedRow(),4);
        }
        try {
            String sql = "UPDATE detail_jual SET jumlah= "+txt_qty.getText()+", sub_total ="+txt_subTtl.getText()+" WHERE nota_penjualan = '"
                    +txt_nota1.getText()
                    +"' AND kode_barang = '"+txt_kode_barang.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        total();
    }//GEN-LAST:event_btn_edit_brgActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from penjualan WHERE nota_penjualan='"+txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        this.setVisible(false);
        new Dashboard().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal_brg;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_cari_brg;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_edit_brg;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_tambah_brg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_gtotal;
    private javax.swing.JTextField txt_harga_brg;
    public static final javax.swing.JTextField txt_kasir = new javax.swing.JTextField();
    private javax.swing.JTextField txt_kode_barang;
    private javax.swing.JTextField txt_nama_brg;
    public static final javax.swing.JTextField txt_nota1 = new javax.swing.JTextField();
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_subTtl;
    private com.toedter.calendar.JDateChooser txt_tgl;
    public static final javax.swing.JLabel username_pnj = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
